# Generated by Django 3.2.11 on 2022-01-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressLegalCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=5, verbose_name='시군구코드')),
                ('legal_code', models.CharField(max_length=5, verbose_name='법정동코드')),
                ('full_code', models.CharField(max_length=10, verbose_name='법정동전체코드')),
                ('address', models.CharField(max_length=50, verbose_name='법정동명')),
            ],
        ),
    ]
